name: Tests on PR
#Nao apagar 

on:
  pull_request: 
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    name: Run lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint

  Test:
    runs-on: ubuntu-latest
    name: Run tests
    needs: Lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test

  Build:
    runs-on: ubuntu-latest
    name: Run build
    needs: Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build
